#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    #----------------------------------------------
    # 如果要换掉默认主题，必须加入colorscheme模块
    # molokai srcery onedark jellybeans palenight one
    # nord gruvbox NeoSolarized hybrid material SpaceVim
    colorscheme = "material"
    colorscheme_bg = "dark"
    #----------------------------------------------

    # 确认下你的终端是否支持真色(不支持则设置为false)
    enable_guicolors = true

    # Disable statusline separator, if you want to use other value, please install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 1
    enable_tabline_filetype_icon = true
    # 是否在状态栏显示当前编辑模式，默认只以颜色进行区分
    enable_statusline_mode = false

    # spacevim 和 vim 会有按键冲突，使用老vim的按键方式
    vimcompatible = true

    # 使用 4 个空格
    default_indent = 4
    # 默认会将tab按键展开为4个空格，若要禁用，设置为false
    expand_tab = true

    # 在文档树中显示版本控制信息
    # enable_filetree_gitstatus = true
    # 文档树的位置
    filetree_direction = "left"

    # 该值为一个List，每一个选项为插件的名称
    disabled_plugins = ["clighter", "clighter8"]

    # 启动时要执行的函数(把leader的修改写在里面)
    bootstrap_before = "myspacevim#before"

    # 自动补全的方式(ycm, neocomplcache, coc, deoplete, asyncomplete, completor)
    autocomplete_method = "ycm"
    # 代码片段的引擎
    snippet_engine = "ultisnips"

[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
    name = "colorscheme"


[[layers]]
    name = "lang#python"

[[layers]]
    # 代码格式化
    name = "format"
